`timescale 1ns / 1ps
// SPDX-FileCopyrightText: 2026 AI_BYTE / Chipathon 2026
// SPDX-License-Identifier: Apache-2.0
//
// A02_A — D10-style user-macro wrapper for organizer A02 variant A.
// Ports match A02_A.def (146 Metal2 abutment pins). Core is ai_byte_top.
// Power: vss_conn / vdd_conn (Metal2→Metal5), placed via LibreLane MACROS.
//
// Regenerated by: python3 scripts/build_a02_d10_style.py

`default_nettype none

module A02_A (
    inout  wire VSS,
    inout  wire VDD,
    output wire clk_PU,
    output wire clk_PD,
    input  wire clk,
    output wire [7:0] data_CS,
    output wire [7:0] data_SL,
    output wire [7:0] data_IE,
    output wire [7:0] data_OE,
    output wire [7:0] data_PU,
    output wire [7:0] data_PD,
    output wire [7:0] data_OUT,
    output wire [7:0] data_PDRV0,
    output wire [7:0] data_PDRV1,
    input  wire [7:0] data_IN,
    output wire [3:0] addr_PU,
    output wire [3:0] addr_PD,
    input  wire [3:0] addr,
    output wire irq_CS,
    output wire irq_SL,
    output wire irq_IE,
    output wire irq_OE,
    output wire irq_PU,
    output wire irq_PD,
    output wire irq_OUT,
    output wire irq_PDRV0,
    output wire irq_PDRV1,
    input  wire irq_IN,
    output wire re_PU,
    output wire re_PD,
    input  wire re,
    output wire [2:0] debug_state_CS,
    output wire [2:0] debug_state_SL,
    output wire [2:0] debug_state_IE,
    output wire [2:0] debug_state_OE,
    output wire [2:0] debug_state_PU,
    output wire [2:0] debug_state_PD,
    output wire [2:0] debug_state_OUT,
    output wire [2:0] debug_state_PDRV0,
    output wire [2:0] debug_state_PDRV1,
    input  wire [2:0] debug_state_IN,
    output wire we_PU,
    output wire we_PD,
    input  wire we,
    output wire rst_n_PU,
    output wire rst_n_PD,
    input  wire rst_n
);

`ifdef USE_POWER_PINS
    (* keep *) (* keep_hierarchy *) vss_conn u_vss_conn (.VSS(VSS));
    (* keep *) (* keep_hierarchy *) vdd_conn u_vdd_conn (.VDD(VDD));
`endif

    wire       data_drive = re & ~we;
    wire [7:0] data_bus;
    wire       irq_core;
    wire [2:0] debug_core;

    genvar di;
    generate
        for (di = 0; di < 8; di = di + 1) begin : g_data
            assign data_bus[di]   = data_drive ? 1'bz : data_IN[di];
            assign data_OUT[di]   = data_bus[di];
            assign data_OE[di]    = data_drive;
            assign data_IE[di]    = ~data_drive;
            assign data_CS[di]    = 1'b0;
            assign data_SL[di]    = 1'b0;
            assign data_PU[di]    = 1'b0;
            assign data_PD[di]    = 1'b0;
            assign data_PDRV0[di] = 1'b0;
            assign data_PDRV1[di] = 1'b0;
        end
    endgenerate

    assign clk_PU   = 1'b0;
    assign clk_PD   = 1'b0;
    assign rst_n_PU = 1'b0;
    assign rst_n_PD = 1'b0;
    assign re_PU    = 1'b0;
    assign re_PD    = 1'b0;
    assign we_PU    = 1'b0;
    assign we_PD    = 1'b0;
    assign addr_PU  = 4'b0;
    assign addr_PD  = 4'b0;

    assign irq_OUT   = irq_core;
    assign irq_OE    = 1'b1;
    assign irq_IE    = 1'b0;
    assign irq_CS    = 1'b0;
    assign irq_SL    = 1'b0;
    assign irq_PU    = 1'b0;
    assign irq_PD    = 1'b0;
    assign irq_PDRV0 = 1'b0;
    assign irq_PDRV1 = 1'b0;

    genvar db;
    generate
        for (db = 0; db < 3; db = db + 1) begin : g_dbg
            assign debug_state_OUT[db]   = debug_core[db];
            assign debug_state_OE[db]    = 1'b1;
            assign debug_state_IE[db]    = 1'b0;
            assign debug_state_CS[db]    = 1'b0;
            assign debug_state_SL[db]    = 1'b0;
            assign debug_state_PU[db]    = 1'b0;
            assign debug_state_PD[db]    = 1'b0;
            assign debug_state_PDRV0[db] = 1'b0;
            assign debug_state_PDRV1[db] = 1'b0;
        end
    endgenerate

    // Keep unused pad loopback inputs referenced (Metal2 pins still exist).
    wire _unused_pad_in = irq_IN | (|debug_state_IN);

    ai_byte_top #(
        .DATA_W(8),
        .REG_ADDR_W(4)
    ) u_core (
`ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
`endif
        .clk(clk),
        .rst_n(rst_n),
        .addr(addr),
        .data(data_bus),
        .we(we),
        .re(re),
        .irq(irq_core),
        .debug_state(debug_core)
    );

endmodule

`default_nettype wire
