MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RUN_TAG = $(shell ls librelane/runs/ | tail -n 1)
TOP = chip_top

# ---------------------------------------------------------------------------
# PDK — OUTSIDE the project so it is not lost with ./gf180mcu cleanups.
# Persistent path:  ~/.cache/ai-byte/pdk/gf180mcu
# Override:  make librelane-core PDK_ROOT=/other/path/gf180mcu
# `:=` ignores ambient shell PDK_ROOT (avoids IHP OpenLane hijacks).
# librelane-core never installs or deletes the PDK.
# ---------------------------------------------------------------------------
PDK_TAG ?= 1.8.0
PDK := gf180mcuD
PDK_ROOT := $(HOME)/.cache/ai-byte/pdk/gf180mcu
export STD_CELL_LIBRARY := gf180mcu_fd_sc_mcu9t5v0
export PAD_CELL_LIBRARY := gf180mcu_fd_io
export SCL := $(STD_CELL_LIBRARY)

AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5 workshop
DEFAULT_SLOT = workshop
SLOT ?= $(DEFAULT_SLOT)

ifeq ($(SLOT),default)
    SLOT = $(DEFAULT_SLOT)
endif

ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
    $(error $(SLOT) does not exist in AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
	@echo ''
	@echo "PDK_ROOT=$(PDK_ROOT)"
	@echo "  (persistent cache; clone once with make clone-pdk)"
.PHONY: help

all: librelane ## Build the project (runs LibreLane)
.PHONY: all

# Marker only exists when wafer-space layout is complete
PDK_MARKER := $(PDK_ROOT)/$(PDK)/libs.tech/librelane/config.tcl
GIT_CLONE = git clone --progress --verbose

clone-pdk: ## Clone PDK once into ~/.cache (never deletes a valid tree)
	@mkdir -p "$$(dirname "$(PDK_ROOT)")"
	@if [ -f "$(PDK_MARKER)" ]; then \
	  echo "PDK OK (already present): $(PDK_ROOT)"; \
	  du -sh "$(PDK_ROOT)"; \
	  echo "Not removed by make librelane / librelane-core."; \
	  echo "Wipe only with: make force-clone-pdk"; \
	elif [ -e "$(PDK_ROOT)" ]; then \
	  echo "ERROR: $(PDK_ROOT) exists but is incomplete."; \
	  echo "  Missing marker: $(PDK_MARKER)"; \
	  echo "Refusing to auto-delete. Either:"; \
	  echo "  mv $(PDK_ROOT) $(PDK_ROOT).broken-$$(date +%s) && make clone-pdk"; \
	  echo "  make force-clone-pdk"; \
	  exit 1; \
	else \
	  echo "Cloning wafer-space/gf180mcu @ $(PDK_TAG) → $(PDK_ROOT)"; \
	  echo "(Receiving objects % — leave this terminal open until 'PDK ready')"; \
	  $(GIT_CLONE) https://github.com/wafer-space/gf180mcu.git "$(PDK_ROOT)" --depth 1 --branch ${PDK_TAG}; \
	  test -f "$(PDK_MARKER)" || { \
	    echo "ERROR: clone ended incomplete; marker missing: $(PDK_MARKER)"; \
	    exit 1; \
	  }; \
	  echo "PDK ready: $(PDK_ROOT)"; \
	  du -sh "$(PDK_ROOT)"; \
	fi
.PHONY: clone-pdk

force-clone-pdk: ## Explicit wipe + re-clone only (slow)
	@echo "WARNING: deleting $(PDK_ROOT) then re-cloning @ ${PDK_TAG}"
	@echo "(Receiving objects % — leave terminal open)"
	rm -rf "$(PDK_ROOT)"
	@mkdir -p "$$(dirname "$(PDK_ROOT)")"
	$(GIT_CLONE) https://github.com/wafer-space/gf180mcu.git "$(PDK_ROOT)" --depth 1 --branch ${PDK_TAG}
	test -f "$(PDK_MARKER)" || { echo "ERROR: incomplete after force clone"; exit 1; }
	@echo "PDK ready: $(PDK_ROOT)"
	@du -sh "$(PDK_ROOT)"
.PHONY: force-clone-pdk

check-pdk: ## Verify PDK exists (no download, no delete)
	@if [ -f "$(PDK_MARKER)" ]; then \
	  echo "OK: PDK_ROOT=$(PDK_ROOT)"; \
	  du -sh "$(PDK_ROOT)" 2>/dev/null || true; \
	else \
	  echo "MISSING PDK at PDK_ROOT=$(PDK_ROOT)"; \
	  echo "Expected: $(PDK_MARKER)"; \
	  echo "Install once:  make clone-pdk"; \
	  echo "(librelane-core does not install or remove the PDK)"; \
	  exit 1; \
	fi
.PHONY: check-pdk

LIBRELANE_COMMON = librelane librelane/slots/slot_${SLOT}.yaml librelane/config.yaml \
	--save-views-to $(MAKEFILE_DIR)/final \
	--pdk ${PDK} --pdk-root ${PDK_ROOT} --scl ${STD_CELL_LIBRARY} --manual-pdk

CORE_SIDE    ?= 1100
CORE_MARGIN  ?= 10
PL_DENSITY   ?= 55
CORE_FINAL   := $(MAKEFILE_DIR)/final_core
CORE_CFG     := $(MAKEFILE_DIR)/librelane/config_ai_byte_core.yaml
CORE_SIZE_YAML := $(MAKEFILE_DIR)/librelane/.core_size_override.yaml

define write_core_size_yaml
	@core_hi=$$(( $(CORE_SIDE) - $(CORE_MARGIN) )); \
	printf '%s\n' \
	  "# auto-generated by Makefile — do not edit" \
	  "FP_SIZING: absolute" \
	  "DIE_AREA: [0, 0, $(CORE_SIDE), $(CORE_SIDE)]" \
	  "CORE_AREA: [$(CORE_MARGIN), $(CORE_MARGIN), $$core_hi, $$core_hi]" \
	  "PL_TARGET_DENSITY_PCT: $(PL_DENSITY)" \
	  > $(CORE_SIZE_YAML); \
	echo "Core floorplan: die=$(CORE_SIDE)×$(CORE_SIDE) µm  " \
	     "core=[$(CORE_MARGIN)..$$core_hi]  density=$(PL_DENSITY)%"; \
	echo "PDK_ROOT=$(PDK_ROOT)"
endef

LIBRELANE_CORE = librelane $(CORE_CFG) $(CORE_SIZE_YAML) \
	--save-views-to $(CORE_FINAL) \
	--pdk ${PDK} --pdk-root ${PDK_ROOT} --scl ${STD_CELL_LIBRARY} --manual-pdk

librelane-core: check-pdk ## Core-only full flow + DRC (PDK must already exist)
	$(write_core_size_yaml)
	$(LIBRELANE_CORE)
.PHONY: librelane-core

librelane-core-nodrc: check-pdk ## Core-only without DRC
	$(write_core_size_yaml)
	$(LIBRELANE_CORE) --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-core-nodrc

librelane: check-pdk ## Full chip LibreLane (padframe)
	$(LIBRELANE_COMMON)
.PHONY: librelane

librelane-nodrc: check-pdk ## Full chip without DRC
	$(LIBRELANE_COMMON) --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-nodrc

librelane-klayoutdrc: check-pdk ## LibreLane without Magic DRC
	$(LIBRELANE_COMMON) --skip Magic.DRC
.PHONY: librelane-klayoutdrc

librelane-magicdrc: check-pdk ## LibreLane without KLayout DRC
	$(LIBRELANE_COMMON) --skip KLayout.DRC
.PHONY: librelane-magicdrc

librelane-openroad: check-pdk ## Open last run in OpenROAD
	librelane librelane/slots/slot_${SLOT}.yaml librelane/config.yaml \
		--pdk ${PDK} --pdk-root ${PDK_ROOT} --scl ${STD_CELL_LIBRARY} --manual-pdk \
		--last-run --flow OpenInOpenROAD
.PHONY: librelane-openroad

librelane-klayout: check-pdk ## Open last run in KLayout
	librelane librelane/slots/slot_${SLOT}.yaml librelane/config.yaml \
		--pdk ${PDK} --pdk-root ${PDK_ROOT} --scl ${STD_CELL_LIBRARY} --manual-pdk \
		--last-run --flow OpenInKLayout
.PHONY: librelane-klayout

librelane-padring: check-pdk ## Only create the padring
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} python3 scripts/padring.py librelane/slots/slot_${SLOT}.yaml librelane/config.yaml
.PHONY: librelane-padring

sim: ## Run RTL simulation with cocotb
	cd cocotb; PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} \
		COCOTB_TEST_MODULES=$${COCOTB_TEST_MODULES:-chip_top_tb,test_ai_byte} \
		python3 chip_top_tb.py
.PHONY: sim

sim-gl: ## Gate-level sim (after copy-final)
	cd cocotb; GL=1 PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} python3 chip_top_tb.py
.PHONY: sim-gl

sim-view: ## View waveforms
	gtkwave cocotb/sim_build/chip_top.fst
.PHONY: sim-view

render-image: ## Render final GDS image
	mkdir -p img/
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} python3 scripts/lay2img.py final/gds/${TOP}.gds img/${TOP}.png --width 2048 --oversampling 4
.PHONY: render-image
