#!/usr/bin/env python3
"""D10-style A02 user-macro artifacts from organizer A02_A.def.

Produces:
  1) librelane/floorplan/A02_A_full.def
     — organizer DEF with UNITS 200 → 2000 (OpenROAD) and all 146 pins kept.
  2) src/a02/A02_A.v
     — pad-control wrapper (ports match DEF names) + ai_byte_top + power connectors.

Same method as D10: FP_DEF_TEMPLATE = organizer contract (unit-scaled only),
wrapper RTL exposes every template pin with OE/IE/PU/… tie-offs / glue.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DEF = ROOT / "A02.def (1)/A02/project_defs/A/A02_A.def"
OUT_DEF = ROOT / "librelane" / "floorplan" / "A02_A_full.def"
OUT_V = ROOT / "src" / "a02" / "A02_A.v"

SRC_UNITS = 200
DST_UNITS = 2000
SCALE = DST_UNITS // SRC_UNITS  # 10


def scale_def(text: str) -> str:
    """Scale all integer coordinate pairs and UNITS; keep DESIGN A02_A."""
    text = re.sub(
        r"UNITS DISTANCE MICRONS \d+",
        f"UNITS DISTANCE MICRONS {DST_UNITS}",
        text,
        count=1,
    )

    def scale_xy(m: re.Match[str]) -> str:
        return f"( {int(m.group(1)) * SCALE} {int(m.group(2)) * SCALE} )"

    # Every DEF coordinate pair: DIEAREA, LAYER rects, FIXED, …
    text = re.sub(r"\( (-?\d+) (-?\d+) \)", scale_xy, text)
    return text


def parse_pins(text: str) -> list[tuple[str, str, str]]:
    return [
        (m.group(1), m.group(2), m.group(3))
        for m in re.finditer(
            r"^- (\S+) \+ NET \S+ \+ DIRECTION (\S+) \+ USE (\S+)",
            text,
            re.M,
        )
    ]


def _bus_groups(pins: list[tuple[str, str, str]]) -> list[str]:
    """Port declaration lines with buses packed from bit pins."""
    bus_re = re.compile(r"^(.+)\[(\d+)\]$")
    groups: dict[str, dict] = {}
    order: list[str] = []

    for name, direction, _use in pins:
        m = bus_re.match(name)
        if m:
            base, idx = m.group(1), int(m.group(2))
            if base not in groups:
                groups[base] = {"dir": direction, "max": idx}
                order.append(base)
            else:
                groups[base]["max"] = max(groups[base]["max"], idx)
                if groups[base]["dir"] != direction:
                    raise SystemExit(f"direction mismatch on {base}")
        else:
            if name not in groups:
                groups[name] = {"dir": direction, "max": None}
                order.append(name)

    decls = []
    for key in order:
        g = groups[key]
        d = {"INPUT": "input ", "OUTPUT": "output", "INOUT": "inout "}[g["dir"]]
        if g["max"] is not None:
            decls.append(f"    {d} wire [{g['max']}:0] {key}")
        else:
            decls.append(f"    {d} wire {key}")
    return decls


def gen_wrapper(pins: list[tuple[str, str, str]]) -> str:
    ports_joined = ",\n".join(_bus_groups(pins))
    return f"""\
`timescale 1ns / 1ps
// SPDX-FileCopyrightText: 2026 AI_BYTE / Chipathon 2026
// SPDX-License-Identifier: Apache-2.0
//
// A02_A — D10-style user-macro wrapper for organizer A02 variant A.
// Ports match A02_A.def (146 Metal2 abutment pins). Core is ai_byte_top.
// Power: vss_conn / vdd_conn (Metal2→Metal5), placed via LibreLane MACROS.
//
// Regenerated by: python3 scripts/build_a02_d10_style.py

`default_nettype none

module A02_A (
{ports_joined}
);

`ifdef USE_POWER_PINS
    (* keep *) (* keep_hierarchy *) vss_conn u_vss_conn (.VSS(VSS));
    (* keep *) (* keep_hierarchy *) vdd_conn u_vdd_conn (.VDD(VDD));
`endif

    wire       data_drive = re & ~we;
    wire [7:0] data_bus;
    wire       irq_core;
    wire [2:0] debug_core;

    genvar di;
    generate
        for (di = 0; di < 8; di = di + 1) begin : g_data
            assign data_bus[di]   = data_drive ? 1'bz : data_IN[di];
            assign data_OUT[di]   = data_bus[di];
            assign data_OE[di]    = data_drive;
            assign data_IE[di]    = ~data_drive;
            assign data_CS[di]    = 1'b0;
            assign data_SL[di]    = 1'b0;
            assign data_PU[di]    = 1'b0;
            assign data_PD[di]    = 1'b0;
            assign data_PDRV0[di] = 1'b0;
            assign data_PDRV1[di] = 1'b0;
        end
    endgenerate

    assign clk_PU   = 1'b0;
    assign clk_PD   = 1'b0;
    assign rst_n_PU = 1'b0;
    assign rst_n_PD = 1'b0;
    assign re_PU    = 1'b0;
    assign re_PD    = 1'b0;
    assign we_PU    = 1'b0;
    assign we_PD    = 1'b0;
    assign addr_PU  = 4'b0;
    assign addr_PD  = 4'b0;

    assign irq_OUT   = irq_core;
    assign irq_OE    = 1'b1;
    assign irq_IE    = 1'b0;
    assign irq_CS    = 1'b0;
    assign irq_SL    = 1'b0;
    assign irq_PU    = 1'b0;
    assign irq_PD    = 1'b0;
    assign irq_PDRV0 = 1'b0;
    assign irq_PDRV1 = 1'b0;

    genvar db;
    generate
        for (db = 0; db < 3; db = db + 1) begin : g_dbg
            assign debug_state_OUT[db]   = debug_core[db];
            assign debug_state_OE[db]    = 1'b1;
            assign debug_state_IE[db]    = 1'b0;
            assign debug_state_CS[db]    = 1'b0;
            assign debug_state_SL[db]    = 1'b0;
            assign debug_state_PU[db]    = 1'b0;
            assign debug_state_PD[db]    = 1'b0;
            assign debug_state_PDRV0[db] = 1'b0;
            assign debug_state_PDRV1[db] = 1'b0;
        end
    endgenerate

    // Keep unused pad loopback inputs referenced (Metal2 pins still exist).
    wire _unused_pad_in = irq_IN | (|debug_state_IN);

    ai_byte_top #(
        .DATA_W(8),
        .REG_ADDR_W(4)
    ) u_core (
`ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
`endif
        .clk(clk),
        .rst_n(rst_n),
        .addr(addr),
        .data(data_bus),
        .we(we),
        .re(re),
        .irq(irq_core),
        .debug_state(debug_core)
    );

endmodule

`default_nettype wire
"""


def main() -> int:
    if not SRC_DEF.is_file():
        print(f"missing {SRC_DEF}", file=sys.stderr)
        return 1

    raw = SRC_DEF.read_text()
    pins = parse_pins(raw)
    if len(pins) != 146:
        print(f"warning: expected 146 pins, got {len(pins)}", file=sys.stderr)

    scaled = scale_def(raw)
    # Sanity: die must be 1110 µm → 2_220_000 dbu @ 2000
    if "DIEAREA ( 0 0 ) ( 2220000 2220000 )" not in scaled:
        print("error: DIEAREA scale failed", file=sys.stderr)
        print(re.search(r"DIEAREA.*", scaled).group(0), file=sys.stderr)  # type: ignore
        return 1

    OUT_DEF.parent.mkdir(parents=True, exist_ok=True)
    OUT_DEF.write_text(scaled)
    print(f"wrote {OUT_DEF}  (UNITS {SRC_UNITS}->{DST_UNITS}, {len(pins)} pins)")

    OUT_V.parent.mkdir(parents=True, exist_ok=True)
    OUT_V.write_text(gen_wrapper(pins))
    print(f"wrote {OUT_V}")
    print("port coverage: bus-packed to match DEF bit names")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
